### ISSUE TITLE
Test with newer pyawair library

### ISSUE THREAD

**Issue by netmanchris** [danielsjf/awair_component#2]
hey @danielsjf 

You've got this pin'd to the 0.0.9 version of the pyawair library.  Can you please test this out with the 0.0.10 version of the library? I've got the tests coverage up to 98% for the library. It's now behaving as I expect it to, but I want to make sure that the Hass driver still works.

**Comment by netmanchris** [comment]
Please test with 0.0.11 to include fixes for Awair Glow not discovering properly

**Comment by danielsjf** [comment]
Works with the latest v0.0.12.
