### ISSUE TITLE
Will this component work with hass.io?

### ISSUE THREAD

**Issue by ryanmboyce** [danielsjf/awair_component#5]
Any idea if this will work under docker and hass.io image?

**Comment by danielsjf** [comment]
I think it should work with any version of HA, but I can certainly confirm it for hassio since that's what I am using.

**Comment by ryanmboyce** [comment]
Awesome thx

**Comment by ryanmboyce** [comment]
Tried to get it working but hass.io complaining with this error:

`2018-11-18 11:37:55 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform awair                                                                                 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform                                                                   
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sensor/awair.py", line 51, in setup_platform
    from pyawair.auth import AwairAuth
ModuleNotFoundError: No module named 'pyawair'`

![image](https://user-images.githubusercontent.com/28747183/48677253-cc14cd00-eb26-11e8-93af-a48809a625cb.png)

**Comment by ryanmboyce** [comment]
Looks like I have to get [pyawair](https://pypi.org/project/pyawair/) installed

**Comment by danielsjf** [comment]
A reboot should normally fix that. I think it installs component modules after a reboot.

**Comment by danielsjf** [comment]
Actually I'm not completely sure what happens. I've had this problem as well in the past. Rebooting solved it for me. The documentation specifies that the dependencies are installed but it doesn't specify when they are installed. This component doesn't use asyncio, so what might happen is that it takes too long to install the module (see the SLOW_SETUP_MAX_WAIT). Using asyncio might solve it, although I'm not certain.

**Comment by ryanmboyce** [comment]
Rebooting ultimately did solve my issue, thanks.
